// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutocompleteController from "./autocomplete_controller"
application.register("autocomplete", AutocompleteController)

import DestinationsController from "./destinations_controller"
application.register("destinations", DestinationsController)

import DisplayMapsController from "./display_maps_controller"
application.register("display-maps", DisplayMapsController)

import SelectStationsController from "./select_stations_controller"
application.register("select-stations", SelectStationsController)
